export interface RecentTransaction {
  id: string;
  id_user: string;
  id_sales: string;
  id_pelanggan: string;
  id_gudang: string;
  no_nota: string;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
  tgl_bayar: string;
  tgl_masuk: string;
  tgl_keluar: string;
  jml_total: string;
  jml_biaya: string;
  jml_ongkir: string;
  jml_retur: string;
  diskon: string;
  jml_diskon: string;
  jml_subtotal: string;
  ppn: string;
  jml_ppn: string;
  jml_gtotal: string;
  jml_bayar: string;
  jml_kembali: string;
  jml_kurang: string;
  disk1: string;
  jml_disk1: string;
  disk2: string;
  jml_disk2: string;
  disk3: string;
  jml_disk3: string;
  metode_bayar: string;
  voucher_code: string | null;
  voucher_discount: string;
  voucher_id: string | null;
  voucher_type: string | null;
  voucher_discount_amount: string;
  status: string;
  qr_scanned: string;
  qr_scan_time: string | null;
  status_nota: string;
  status_ppn: string;
  status_bayar: string;
  status_retur: string;
}
